source 'https://rubygems.org'

ruby '2.0.0'

gem 'bubble-wrap', :require => false
gem 'cocoapods'
gem 'motion-cocoapods'
gem 'motion-layout'

group :development do
  gem 'rake'
  gem 'sugarcube', :require => false
end
